export const MESSAGE_ADD = "MESSAGE_ADD";
export const MESSAGE_ADD_ALL = "MESSAGE_ADD_ALL";
export const MESSAGE_REMOVE = "MESSAGE_REMOVE";
export const MESSAGE_REMOVE_ALL = "MESSAGE_REMOVE_ALL";

export const CHANGE_ACCOUNT = "CHANGE_ACCOUNT";

export const TAKE_MY_MONEY = "TAKE_MY_MONEY";

export const SWITCH_LANGUAGE = "SWITCH_LANGUAGE";
